'use client';
import { useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useState } from 'react';
const Input = (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props}/>;
function Form(){const query=useSearchParams();const [code,setCode]=useState(query.get('code')||''),[roll,setRoll]=useState(''),[pin,setPin]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[showPin,setShowPin]=useState(false);const hasQr=!!query.get('session')&&!!query.get('token');
useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool||!hasQr)return;const controller=new AbortController();const tool={name:'complete_attendance_check_in',title:'Check in to class',description:'Submit the student roll number and private PIN using the current scanned QR link.',inputSchema:{type:'object',properties:{classCode:{type:'string'},roll:{type:'string'},pin:{type:'string'}},required:['classCode','roll','pin'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const d=input as {classCode?:string,roll?:string,pin?:string};if(!d.classCode||!d.roll||!/^\d{6}$/.test(d.pin||''))throw new Error('Class code, roll number, and six-digit PIN are required.');const res=await fetch('/api/check-in',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:d.classCode,roll:d.roll,pin:d.pin,sessionId:query.get('session'),token:query.get('token')})});const result=await res.json() as {error?:string,already?:boolean};if(!res.ok)throw new Error(result.error||'Check-in failed');setSuccess(true);setMessage(result.already?'You were already checked in for this session.':'You’re checked in. Your teacher can see your attendance now.');return {checkedIn:true,already:!!result.already}}};try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[query,hasQr]);
async function submit(e:React.FormEvent){e.preventDefault();if(!hasQr||busy)return;setBusy(true);setMessage('');try{const res=await fetch('/api/check-in',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,roll,pin,sessionId:query.get('session'),token:query.get('token')})});const d=await res.json() as {error?:string,already?:boolean};if(!res.ok)throw new Error(d.error);setSuccess(true);setMessage(d.already?'You were already checked in for this session.':'You’re checked in. Your teacher can see your attendance now.')}catch(e){setMessage(e instanceof Error?e.message:'Could not check in.')}finally{setBusy(false)}}
return <main className="check-shell"><a className="brand" href="/"><img className="brand-mark" src="/favicon.svg" width="34" height="34" alt="" />classroll</a><section className="panel"><p className="eyebrow">STUDENT CHECK-IN</p><h1>{success?'All set.':hasQr?'Mark yourself present.':'Scan your teacher’s QR.'}</h1><p className="muted">{success?'Your attendance has been recorded. You can close this page.':hasQr?'Enter your roll number and the private PIN your teacher gave you.':'Open your phone’s camera and scan the QR code displayed by your teacher. It will open this page with your session ready.'}</p>{message&&<div role={success?'status':'alert'} className={'notice '+(success?'success':'error')} style={{margin:'20px 0'}}>{message}</div>}{!success&&hasQr&&<form className="stack" onSubmit={submit}><label className="field">Class code<Input readOnly={!!query.get('code')} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required autoComplete="off" /></label><label className="field">Roll number<Input value={roll} onChange={e=>setRoll(e.target.value)} required autoComplete="off" /></label><label className="field">Your 6-digit PIN<div className="password-control"><Input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" type={showPin?'text':'password'} required autoComplete="off" /><button className="text-button" type="button" aria-pressed={showPin} onClick={()=>setShowPin(!showPin)}>{showPin?'Hide':'Show'}</button></div><span className="field-hint">Forgot your PIN? Ask your teacher to reset it.</span></label><button className="button primary" disabled={busy}>{busy?'Checking in…':'Confirm attendance'}</button></form>}<p className="tiny" style={{marginTop:22}}>No phone or no connection? Tell your teacher so they can record your attendance with a reason.</p></section><a className="back-link" href="/">Back to home</a></main>}
export default function CheckIn(){return <Suspense fallback={<main className="check-shell">Loading check-in…</main>}><Form/></Suspense>}
