'use client';
import { useCallback, useEffect, useState, useRef, useId } from 'react';
import QRCode from 'qrcode';
const Input = (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props}/>;


type Klass={id:string,name:string,code:string,timezone:string};
type Student={id:string,name:string,roll:string,email?:string|null,account_id?:string|null};
type RecordRow={student_id:string,status:string,method:string,checked_at:number,note:string|null};
type StudentDetail={student:Student,className:string,history:{date:string,status:string|null,method:string|null,checked_at:number|null,note:string|null}[]};
type State={teacher:{id:string,name:string}|null,invited?:boolean,hasTeacher?:boolean,classes?:Klass[],archivedClasses?:{id:string,name:string}[],students?:Student[],archivedStudents?:Student[],session?:{id:string,date:string,startsAt:number,endsAt:number,closedAt:number|null,open:boolean,token:string|null}|null,attendance?:RecordRow[],invitations?:{email:string}[]};
function Modal({title,onClose,busy,children}:{title:string,onClose:()=>void,busy:boolean,children:React.ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null), titleId=useId();
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog?.close();document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus()}},[]);
  return <dialog ref={ref} className="access-dialog" aria-labelledby={titleId} onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="dialog-content"><div className="panel-head"><h2 id={titleId}>{title}</h2><button className="button outline" disabled={busy} onClick={onClose}>Close</button></div>{children}</div></dialog>
}
export default function TeacherApp({name}:{name:string}) {
  const [selectedDate,setSelectedDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[state,setState]=useState<State|null>(null),[classId,setClassId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pin,setPin]=useState<{name:string,roll:string,pin:string}|null>(null),[qr,setQr]=useState('');
  const [notice,setNotice]=useState(''),[invite,setInvite]=useState<{email:string,code:string}|null>(null),[className,setClassName]=useState(''),[studentName,setStudentName]=useState(''),[roll,setRoll]=useState(''),[studentEmail,setStudentEmail]=useState(''),[linkEmail,setLinkEmail]=useState(''),[email,setEmail]=useState(''),[minutes,setMinutes]=useState('20');
  const [modal,setModal]=useState<'newClass'|'addStudent'|'invite'|'manage'|'student'|'correction'|'pin'|'qr'|null>(null);
  const [correction,setCorrection]=useState<{id:string,name:string}|null>(null),[status,setStatus]=useState('present'),[reason,setReason]=useState(''),[copyFeedback,setCopyFeedback]=useState('');
  const detailRequest=useRef(0),refreshRequest=useRef(0);
  const [loadError,setLoadError]=useState('');
  const [studentSearch,setStudentSearch]=useState(''),[detail,setDetail]=useState<StudentDetail|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState('');
  async function openStudent(studentId:string){if(!active)return;const requestId=++detailRequest.current;setModal('student');setError('');setPin(null);setDetail(null);setDetailError('');setDetailLoading(true);try{const res=await fetch('/api/teacher?classId='+encodeURIComponent(active.id)+'&studentId='+encodeURIComponent(studentId),{cache:'no-store'});const data=await res.json() as StudentDetail & {error?:string};if(!res.ok)throw new Error(data.error||'Could not load student');if(requestId===detailRequest.current){setDetail(data);setLinkEmail(data.student.email||'')}}catch(e){if(requestId===detailRequest.current)setDetailError(e instanceof Error?e.message:'Could not load student')}finally{if(requestId===detailRequest.current)setDetailLoading(false)}}
  const refresh=useCallback(async (chosen?:string)=>{const requestId=++refreshRequest.current;try{const res=await fetch('/api/teacher?classId='+encodeURIComponent(chosen??classId)+'&date='+encodeURIComponent(selectedDate),{cache:'no-store'});const d=await res.json() as State & {error?:string,pin?:string,name?:string,roll?:string,classId?:string,inviteCode?:string,email?:string};if(!res.ok)throw new Error(d.error);if(requestId!==refreshRequest.current)return;setState(d);const next=d.classes?.find(c=>c.id===(chosen??classId))||d.classes?.[0];setClassId(next?.id||'');setLoadError('')}catch(e){if(requestId===refreshRequest.current)setLoadError(e instanceof Error?e.message:'Could not load attendance')}},[classId,selectedDate]);
  useEffect(()=>{refresh();const timer=setInterval(()=>refresh(),15000);return()=>clearInterval(timer)},[refresh]);
  const active=state?.classes?.find(c=>c.id===classId)||state?.classes?.[0];
  useEffect(()=>{if(!state?.session?.open||!state.session.token||!active){setQr('');return}const url=new URL('/check-in',window.location.origin);url.searchParams.set('code',active.code);url.searchParams.set('session',state.session.id);url.searchParams.set('token',state.session.token);QRCode.toDataURL(url.toString(),{width:320,margin:1,color:{dark:'#15243c',light:'#ffffff'}}).then(setQr).catch(()=>setQr(''))},[state?.session?.token,state?.session?.id,state?.session?.open,active?.code]);
  async function act(action:string,extra:Record<string,unknown>={}){if(busy)return false;setBusy(true);setError('');setCopyFeedback('');try{const res=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,classId:active?.id,date:selectedDate,...extra})});const d=await res.json() as {error?:string,pin?:string,name?:string,roll?:string,classId?:string,inviteCode?:string,email?:string};if(!res.ok)throw new Error(d.error||'Could not save');if(d.inviteCode)setInvite({email:d.email||'',code:d.inviteCode});if(d.pin){setPin({name:d.name||'',roll:d.roll||'',pin:d.pin});setModal('pin');}if(d.classId)setClassId(d.classId);if(action==='archiveClass')setClassId('');await refresh(action==='archiveClass'?'':d.classId||active?.id);setNotice(action==='addStudent'?'Student added':action==='resetPin'?'PIN reset':action==='archiveClass'?'Class archived':action==='archiveStudent'?'Student archived':action==='restoreClass'?'Class restored':action==='restoreStudent'?'Student restored':'Saved');return true}catch(e){setError(e instanceof Error?e.message:'Could not save');return false}finally{setBusy(false)}}
  const searchText=studentSearch.trim().toLocaleLowerCase();const matchingStudents=(state?.students||[]).filter(s=>s.name.toLocaleLowerCase().includes(searchText)||s.roll.toLocaleLowerCase().includes(searchText));const matchingArchived=(state?.archivedStudents||[]).filter(s=>s.name.toLocaleLowerCase().includes(searchText)||s.roll.toLocaleLowerCase().includes(searchText));
  const records=new Map((state?.attendance||[]).map(r=>[r.student_id,r]));const visibleIds=new Set((state?.students||[]).map(s=>s.id));const present=[...records.values()].filter(r=>visibleIds.has(r.student_id)&&(r.status==='present'||r.status==='late')).length;
  function exportCsv(){if(!active||!state?.session)return;const rows=[['Class','Date','Roll','Student','Status','Method','Checked at','Note'],...(state.students||[]).map(s=>{const r=records.get(s.id);return [active.name,state.session!.date,s.roll,s.name,r?.status||'absent',r?.method||'',r?new Date(r.checked_at).toLocaleString():'',r?.note||'']})];const csv=rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='attendance-'+active.code+'-'+state.session.date+'.csv';a.click();URL.revokeObjectURL(url)}
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:active?.timezone||'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const chooseDate=(date:string)=>{if(date&&date!==selectedDate){refreshRequest.current++;setState(null);setSelectedDate(date)}};
  const openDialog=(value:typeof modal)=>{setError('');setCopyFeedback('');setModal(value)};
  const closeDialog=()=>{detailRequest.current++;setModal(null);setError('');setCopyFeedback('');setPin(null)};
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setCopyFeedback('Copied to clipboard.')}catch{setCopyFeedback('Select the code below and copy it manually.')}}
  const resetPin=async(student:Student)=>{if(confirm('Reset the PIN for '+student.name+'? The previous PIN will stop working.'))await act('resetPin',{studentId:student.id})};
  const rowStatus=(id:string)=>records.get(id)?.status||(state?.session?(state.session.open?'Not checked in':'absent'):'No session');
  const modalTitle=modal==='newClass'?'Create a new class':modal==='addStudent'?'Add a student':modal==='invite'?'Invite a teacher':modal==='manage'?'Manage classes':modal==='student'?(detail?.student.name||'Student details'):modal==='correction'?'Update attendance':modal==='pin'?'Save this student’s PIN':'Classroom QR';
  return <>
    <a className="skip-link" href="#workspace">Skip to attendance</a>
    <header className="topbar"><div className="topbar-inner"><a className="brand" href="/"><img className="brand-mark" src="/favicon.svg" width="34" height="34" alt=""/>classroll</a><nav aria-label="Account"><span>{name}</span><button className="text-button" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});window.location.href='/'}}>Sign out</button></nav></div></header>
    <main className="workspace" id="workspace">
      <div className="page-head"><div><p className="eyebrow">TEACHER WORKSPACE</p><h1>Attendance overview</h1><p className="muted">Your classes, students, and daily attendance.</p></div><button className="button primary" disabled={!state?.teacher||busy} onClick={()=>openDialog('newClass')}>＋ New class</button></div>
      <div className="workspace-toolbar" aria-label="Class tools">
        <label className="field">Class<select value={active?.id||''} disabled={!active||busy} onChange={e=>{refreshRequest.current++;setState(null);setClassId(e.target.value);setStudentSearch('');setPin(null)}}>{!active&&<option value="">No active classes</option>}{state?.classes?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label className="field">Attendance date<input type="date" max={today} value={selectedDate} onChange={e=>chooseDate(e.target.value)}/></label>
        {selectedDate!==today&&<button className="button outline" onClick={()=>chooseDate(today)}>Back to today</button>}
        <div className="toolbar-actions"><button className="button outline" disabled={!active||busy} onClick={()=>openDialog('addStudent')}>＋ Add student</button><a className="button outline" href={active?'/teacher/tasks?classId='+encodeURIComponent(active.id):'/teacher/tasks'}>Class tasks</a><button className="button outline" disabled={!state?.teacher||busy} onClick={()=>openDialog('invite')}>Invite teacher</button><button className="button outline" disabled={!state?.teacher||busy} onClick={()=>openDialog('manage')}>Manage classes</button></div>
      </div>
      {loadError&&<div className="notice error" role="alert">{loadError} <button className="text-button" onClick={()=>refresh()}>Retry</button></div>}
      {error&&!modal&&<div className="notice error" role="alert">{error}</div>}
      {notice&&<div className="notice success feedback-bar" role="status"><span>{notice}</span><button className="text-button" onClick={()=>setNotice('')} aria-label="Dismiss notification">Dismiss</button></div>}
      {!state?<div className="panel" role="status">Loading your classes…</div>:!state.teacher?<div className="panel"><a className="button primary" href="/teacher">Sign in again</a></div>:!active?<section className="panel empty-state"><h2>Create your first class</h2><p>Add your students, then start a session to display the daily QR code.</p><button className="button primary" onClick={()=>openDialog('newClass')}>＋ Create a class</button>{!!state.archivedClasses?.length&&<button className="button outline" onClick={()=>openDialog('manage')}>View archived classes</button>}</section>:<>
        {selectedDate!==today&&<div className="notice history-notice">Viewing attendance for {selectedDate}. Add students and class management apply to the current roster.</div>}
        <div className="attendance-layout">
          <section className="panel session-panel" aria-labelledby="session-heading"><div className="panel-head"><h2 id="session-heading">{selectedDate===today?'Today’s session':'Session record'}</h2><span className={'pill '+(state.session?.open?'present':'')}>{state.session?(state.session.open?'Open':'Closed'):'No session'}</span></div>
            <p className="class-caption">{active.name}</p><div className="class-code"><span>Class code</span><code>{active.code}</code><button className="text-button" onClick={()=>copy(active.code)} aria-label="Copy class code">Copy</button></div>{copyFeedback&&!modal&&<p role="status" className="tiny">{copyFeedback}</p>}
            <div className="stats"><div className="stat"><strong>{present}</strong><span>Attended</span></div><div className="stat"><strong>{state.students?.length||0}</strong><span>Students</span></div></div>
            {!state.session?selectedDate===today?<form className="stack session-form" onSubmit={async e=>{e.preventDefault();await act('start',{minutes})}}><label className="field">Session length (minutes)<input type="number" required min="5" max="120" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><button className="button primary" disabled={busy||!state.students?.length}>{busy?'Please wait…':'Start today’s session'}</button>{!state.students?.length?<p className="tiny">Add a student to your class to get started.</p>:<p className="tiny">Starting opens student check-in and displays a QR code.</p>}</form>:<p className="muted">No session was recorded on this date.</p>:<><p className="tiny">{state.session.date} · {new Date(state.session.startsAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}–{new Date(state.session.endsAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</p>{state.session.open?<><div className="qr-box">{qr?<img src={qr} width="240" height="240" alt="Scan to check in to this class"/>:<p>Preparing QR…</p>}</div><button className="button outline full-width" onClick={()=>openDialog('qr')}>Enlarge QR for classroom</button><p className="tiny">Refreshes automatically. Students scan, then use their own roll number and PIN.</p><button className="button danger full-width" disabled={busy} onClick={()=>{if(confirm('Close today’s session? Students will no longer be able to check in.'))act('close')}}>Close session</button></>:<p className="muted">Check-in is closed. Use “Update” in the roster for corrections with a reason.</p>}</>}
          </section>
          <section className="panel roster-panel" aria-labelledby="roster-heading"><div className="panel-head"><div><h2 id="roster-heading">Roster & attendance</h2><p className="tiny">Select a name for history and student actions.</p></div><button className="button outline" disabled={!state.session} title={state.session?'Download all students for this date':'Start a session to export attendance'} onClick={exportCsv}>Export CSV</button></div>
            <div className="roster-search"><label className="search-field" htmlFor="student-search"><span aria-hidden="true">⌕</span><input id="student-search" aria-label="Search students by name or roll number" type="search" placeholder="Search name or roll number" value={studentSearch} onChange={e=>setStudentSearch(e.target.value)}/></label>{studentSearch&&<button className="text-button" onClick={()=>setStudentSearch('')}>Clear</button>}<span className="search-count" aria-live="polite">{matchingStudents.length} of {state.students?.length||0} students</span></div>
            {!state.students?.length?<div className="empty-state"><h3>{selectedDate===today?'No students here yet':'No roster for this date'}</h3><p>{selectedDate===today?'Add the first student to start taking attendance.':'Choose today to manage the current roster.'}</p><button className="button primary" onClick={()=>selectedDate===today?openDialog('addStudent'):chooseDate(today)}>{selectedDate===today?'＋ Add student':'Back to today'}</button></div>:!matchingStudents.length?<div className="empty-state"><strong>No matching students</strong><p>Try another name or roll number.</p><button className="button outline" onClick={()=>setStudentSearch('')}>Clear search</button></div>:<div className="table-wrap" tabIndex={0} aria-label="Student attendance table"><table><thead><tr><th scope="col">Roll</th><th scope="col">Student</th><th scope="col">Attendance</th><th scope="col">Actions</th></tr></thead><tbody>{matchingStudents.map(s=><tr key={s.id}><td>{s.roll}</td><td><button className="student-link" onClick={()=>openStudent(s.id)}>{s.name}</button></td><td><span className={'pill '+(records.get(s.id)?.status||(state.session&&!state.session.open?'absent':''))}>{rowStatus(s.id)}</span>{records.get(s.id)?.note&&<p className="tiny attendance-note">{records.get(s.id)?.note}</p>}</td><td><div className="student-actions"><button className="micro-button" disabled={busy} onClick={()=>resetPin(s)} aria-label={'Reset PIN for '+s.name}>Reset PIN</button>{state.session&&<button className="micro-button" disabled={busy} onClick={()=>{setCorrection({id:s.id,name:s.name});setStatus(records.get(s.id)?.status||'present');setReason('');openDialog('correction')}} aria-label={'Update attendance for '+s.name}>Update</button>}</div></td></tr>)}</tbody></table></div>}
            {!!state.archivedStudents?.length&&<details className="archive-disclosure"><summary>Archived students ({state.archivedStudents.length})</summary><p className="tiny">Restore a student to let them check in again. Search above also filters this list.</p>{matchingArchived.length?matchingArchived.map(s=><div className="archive-row" key={s.id}><span>{s.name} · {s.roll}</span><button className="button outline" disabled={busy} onClick={()=>act('restoreStudent',{studentId:s.id})}>Restore</button></div>):<p className="muted">No archived students match your search.</p>}</details>}
          </section>
        </div>
      </>}
      {modal&&<Modal key={modal} title={modalTitle} onClose={closeDialog} busy={busy}>
        {error&&<div className="notice error" role="alert">{error}</div>}
        {copyFeedback&&<p className="notice" role="status">{copyFeedback}</p>}
        {modal==='newClass'&&<form className="stack" onSubmit={async e=>{e.preventDefault();if(await act('createClass',{name:className})){setClassName('');chooseDate(today);closeDialog()}}}><p className="muted">Create a class, then add its students.</p><label className="field">Class name<input autoFocus required maxLength={80} placeholder="e.g. Mathematics 11A" value={className} onChange={e=>setClassName(e.target.value)}/></label><button className="button primary" disabled={busy||!className.trim()}>{busy?'Creating…':'Create class'}</button></form>}
        {modal==='addStudent'&&<form className="stack" onSubmit={async e=>{e.preventDefault();if(await act('addStudent',{name:studentName,roll,email:studentEmail})){setStudentName('');setRoll('');setStudentEmail('')}}}><p className="muted">Adding to <strong>{active?.name}</strong>. The student creates an account with this email, then joins using the class code, roll number and private PIN.</p><label className="field">Full name<input autoFocus required maxLength={80} value={studentName} onChange={e=>setStudentName(e.target.value)}/></label><label className="field">Roll number<input required maxLength={30} value={roll} onChange={e=>setRoll(e.target.value)}/></label><label className="field">Student email<input required type="email" value={studentEmail} onChange={e=>setStudentEmail(e.target.value)}/></label><button className="button primary" disabled={busy||!studentName.trim()||!roll.trim()||!studentEmail.trim()}>{busy?'Adding…':'Add student & generate PIN'}</button></form>}
        {modal==='pin'&&pin&&<div className="stack"><p className="muted"><strong>{pin.name}</strong> · Roll {pin.roll}</p><div className="secret-code">{pin.pin}</div><p className="muted">Give this PIN privately to the student. Copy it before closing; it cannot be shown again.</p><button className="button primary" onClick={()=>copy(pin.pin)}>Copy PIN</button><button className="button outline" onClick={closeDialog}>I’ve saved it</button><button className="text-button" onClick={()=>{setPin(null);openDialog('addStudent')}}>Add another student</button></div>}
        {modal==='invite'&&<div className="stack"><p className="muted">Invited teachers create their own accounts and see only classes they create.</p><form className="stack" onSubmit={async e=>{e.preventDefault();if(await act('invite',{email}))setEmail('')}}><label className="field">Teacher’s email<input autoFocus required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="button primary" disabled={busy}>{busy?'Creating…':'Create invitation code'}</button></form>{invite&&<div className="notice success"><p>Send this code privately to <strong>{invite.email}</strong>. They use it when creating their account.</p><code className="wrap-code">{invite.code}</code><button className="button outline" onClick={()=>copy(invite.code)}>Copy invitation code</button></div>}{!!state?.invitations?.length&&<p className="tiny">Pending: {state.invitations.map(x=>x.email).join(', ')}</p>}</div>}
        {modal==='manage'&&<div className="stack">{active&&<><p className="muted">Current class: <strong>{active.name}</strong></p><button className="button danger" disabled={busy} onClick={()=>{if(confirm('Archive '+active.name+'? Its session will close. Attendance history is kept and you can restore the class later.'))act('archiveClass')}}>Archive {active.name}</button></>}<h3>Archived classes</h3>{state?.archivedClasses?.length?state.archivedClasses.map(c=><div className="archive-row" key={c.id}><span>{c.name}</span><button className="button outline" disabled={busy} onClick={()=>act('restoreClass',{classId:c.id})}>Restore</button></div>):<p className="muted">No archived classes.</p>}</div>}
        {modal==='correction'&&correction&&<form className="stack" onSubmit={async e=>{e.preventDefault();if(await act('manual',{studentId:correction.id,status,note:reason}))closeDialog()}}><p className="muted">{correction.name} · {selectedDate}</p><label className="field">Attendance<select value={status} onChange={e=>setStatus(e.target.value)}><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select></label><label className="field">Reason<textarea autoFocus required maxLength={200} rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. Student attended but their phone was unavailable"/></label><button className="button primary" disabled={busy||!reason.trim()}>{busy?'Saving…':'Save attendance'}</button></form>}
        {modal==='student'&&(detailLoading?<p role="status">Loading student…</p>:detailError?<div role="alert" className="notice error">{detailError}</div>:detail&&<div className="stack"><p className="muted">{detail.className} · Roll {detail.student.roll}</p><div className="row"><button className="button outline" disabled={busy} onClick={()=>resetPin(detail.student)}>Reset student PIN</button><button className="button danger" disabled={busy} onClick={async()=>{if(confirm('Archive '+detail.student.name+'? Attendance history is kept.')){if(await act('archiveStudent',{studentId:detail.student.id}))closeDialog()}}}>Archive student</button></div><div className="stats"><div className="stat"><strong>{detail.history.filter(h=>h.status==='present'||h.status==='late').length}</strong><span>Attended</span></div><div className="stat"><strong>{detail.history.length}</strong><span>Sessions</span></div><div className="stat"><strong>{detail.history.length?Math.round(100*detail.history.filter(h=>h.status==='present'||h.status==='late').length/detail.history.length)+'%':'—'}</strong><span>Attendance</span></div></div><h3>Session history</h3>{detail.history.length?<><p className="tiny">Attendance includes present and late records across all listed sessions.</p><div className="table-wrap" tabIndex={0}><table><thead><tr><th>Date</th><th>Status</th><th>Method</th><th>Time</th><th>Note</th></tr></thead><tbody>{detail.history.map(h=><tr key={h.date}><td>{h.date}</td><td><span className={'pill '+(h.status||'absent')}>{h.status||'Absent'}</span></td><td>{h.method||'—'}</td><td>{h.checked_at?new Date(h.checked_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'—'}</td><td>{h.note||'—'}</td></tr>)}</tbody></table></div></>:<p className="muted">No sessions recorded since this student joined.</p>}</div>)}
        {modal==='student'&&detail&&<form className="stack student-email-form" onSubmit={async e=>{e.preventDefault();if(await act('setStudentEmail',{studentId:detail.student.id,email:linkEmail})){setDetail({...detail,student:{...detail.student,email:linkEmail}})}}}><h3>Student portal access</h3><p className="tiny">Set the email used for the student’s account. Changing it disconnects the previous account; the student joins again with their PIN.</p><label className="field">Student email<input required type="email" value={linkEmail} onChange={e=>setLinkEmail(e.target.value)}/></label><button className="button outline" disabled={busy||!linkEmail.trim()}>Save email</button></form>}
        {modal==='qr'&&<div className="classroom-display"><p>{active?.name}</p>{state?.session?.open&&qr?<img src={qr} width="480" height="480" alt="Scan this QR to mark attendance"/>:<p className="notice">This session has ended. Check-in is closed.</p>}<p>Class code: <strong>{active?.code}</strong></p><p className="muted">Scan with your camera, then enter your roll number and private PIN.</p></div>}
      </Modal>}
    </main>
  </>;
}
