'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';

type Klass={id:string,name:string,code:string};
type Task={id:string,name:string,due_date:string,description:string|null};
type Student={id:string,name:string,roll:string};
type Mark={task_id:string,student_id:string,status:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export default function TeacherTasks({name}:{name:string}){
 const [classes,setClasses]=useState<Klass[]>([]),[classId,setClassId]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[students,setStudents]=useState<Student[]>([]),[marks,setMarks]=useState<Mark[]>([]),[selected,setSelected]=useState(''),[search,setSearch]=useState('');
 const [title,setTitle]=useState(''),[date,setDate]=useState(today()),[description,setDescription]=useState(''),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async(id:string)=>{if(!id){setTasks([]);setStudents([]);setMarks([]);setLoading(false);return}setLoading(true);try{const res=await fetch('/api/tasks?classId='+encodeURIComponent(id),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error);setTasks(data.tasks);setStudents(data.students);setMarks(data.marks);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load tasks')}finally{setLoading(false)}},[]);
 useEffect(()=>{let alive=true;(async()=>{try{const r=await fetch('/api/teacher',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);if(!alive)return;setClasses(d.classes||[]);const requested=new URLSearchParams(window.location.search).get('classId');setClassId((d.classes||[]).find((c:Klass)=>c.id===requested)?.id||d.classes?.[0]?.id||'')}catch(e){if(alive){setError(e instanceof Error?e.message:'Could not load classes');setLoading(false)}}})();return()=>{alive=false}},[]);
 useEffect(()=>{load(classId)},[classId,load]);
 const active=classes.find(c=>c.id===classId),current=tasks.find(t=>t.id===selected)||tasks[0],q=search.trim().toLocaleLowerCase(),filtered=students.filter(s=>s.name.toLocaleLowerCase().includes(q)||s.roll.toLocaleLowerCase().includes(q));
 useEffect(()=>{if(tasks.length&&!tasks.some(t=>t.id===selected))setSelected(tasks[0].id);if(!tasks.length)setSelected('')},[tasks,selected]);
 async function action(action:string,extra:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,classId,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(classId);setNotice(action==='mark'?'Status saved':action==='delete'?'Task deleted':'Task saved');return d}catch(e){setError(e instanceof Error?e.message:'Could not save');return null}finally{setBusy(false)}}
 function edit(t:Task){setEditing(t.id);setTitle(t.name);setDate(t.due_date);setDescription(t.description||'');document.getElementById('task-form')?.scrollIntoView({behavior:'smooth',block:'center'})}
 function reset(){setEditing('');setTitle('');setDate(today());setDescription('')}
 function csv(){if(!active||!current)return;const rows=[['Class','Task','Due date','Roll','Student','Status'],...students.map(s=>[active.name,current.name,current.due_date,s.roll,s.name,marks.find(m=>m.task_id===current.id&&m.student_id===s.id)?.status||'unmarked'])];const cell=(value:string)=>{const safe=/^[=+\-@\t\r]/.test(value)?"'"+value:value;return '"'+safe.replaceAll('"','""')+'"'};const blob=new Blob([rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='task-'+active.code+'-'+current.due_date+'.csv';a.click();URL.revokeObjectURL(url)}
 const submitted=(taskId:string)=>students.filter(s=>marks.some(m=>m.task_id===taskId&&m.student_id===s.id&&m.status==='submitted')).length;
 return <><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/"><img className="brand-mark" src="/favicon.svg" alt="" width="34" height="34"/>classroll</Link><nav><span>{name}</span><Link href="/teacher" className="text-button">Attendance</Link></nav></div></header><main className="workspace"><div className="page-head"><div><p className="eyebrow">TEACHER WORKSPACE</p><h1>Class tasks</h1><p className="muted">Track submissions for each class.</p></div><div className="row">{active&&<button className="button primary" onClick={()=>document.getElementById('task-form')?.scrollIntoView({behavior:'smooth',block:'start'})}>＋ New task</button>}<Link href="/teacher" className="button outline">← Attendance</Link></div></div>
 {error&&<div className="notice error" role="alert">{error}</div>}{notice&&<div className="notice success" role="status">{notice}</div>}
 <div className="workspace-toolbar"><label className="field">Class<select value={classId} onChange={e=>{setClassId(e.target.value);setSearch('');reset()}}>{!classes.length&&<option value="">No active classes</option>}{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Link href="/teacher" className="button outline">Manage students in attendance</Link></div>
 {!active?<div className="panel empty-state"><h2>Create a class first</h2><p>Tasks belong to a class and its roster.</p><Link className="button primary" href="/teacher">Open teacher workspace</Link></div>:<div className="task-layout"><div className="task-sidebar"><section className="panel"><div className="panel-head"><h2>Tasks</h2><span className="pill">{tasks.length}</span></div>{loading?<p>Loading…</p>:tasks.length?tasks.map(t=><button key={t.id} className={'task-item '+(current?.id===t.id?'active':'')} onClick={()=>{setSelected(t.id);setSearch('')}}><span><strong>{t.name}</strong><small>Due {t.due_date}</small></span><span className="pill present">{submitted(t.id)}/{students.length}</span></button>):<p className="muted">No tasks yet. Create the first one below.</p>}</section><section className="panel stack" id="task-form"><h2>{editing?'Edit task':'New task'}</h2><form className="stack" onSubmit={async e=>{e.preventDefault();const d=await action(editing?'edit':'create',{taskId:editing,name:title,dueDate:date,description});if(d){if(d.taskId)setSelected(d.taskId);reset()}}}><label className="field">Task name<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Notebook submission: Newton’s laws"/></label><label className="field">Due date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Description (optional)<textarea rows={3} maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button primary" disabled={busy||!title.trim()||!date}>{editing?'Save changes':'Create task'}</button>{editing&&<button type="button" className="button outline" onClick={reset}>Cancel editing</button>}</form></section></div>
 <section className="panel"><div className="panel-head"><div><h2>{current?.name||'Submission list'}</h2>{current&&<p className="muted">Due {current.due_date}{current.description?' · '+current.description:''}</p>}</div>{current&&<div className="row"><button className="button outline" onClick={()=>edit(current)}>Edit</button><button className="button outline" onClick={csv}>Export CSV</button><button className="button danger" disabled={busy} onClick={async()=>{if(confirm('Delete this task and all its submission marks? This cannot be undone.'))await action('delete',{taskId:current.id})}}>Delete</button></div>}</div>
 {current?<><div className="stats"><div className="stat"><strong>{submitted(current.id)}</strong><span>Submitted</span></div><div className="stat"><strong>{students.filter(s=>marks.some(m=>m.task_id===current.id&&m.student_id===s.id&&m.status==='missing')).length}</strong><span>Not submitted</span></div><div className="stat"><strong>{students.filter(s=>!marks.some(m=>m.task_id===current.id&&m.student_id===s.id)).length}</strong><span>Unmarked</span></div><div className="stat"><strong>{students.length}</strong><span>Students</span></div></div><label className="field task-search">Search students<input type="search" placeholder="Name or roll number" value={search} onChange={e=>setSearch(e.target.value)}/></label>{students.length?<div className="table-wrap"><table><thead><tr><th>Roll</th><th>Student</th><th>Submission</th></tr></thead><tbody>{filtered.map(s=>{const status=marks.find(m=>m.task_id===current.id&&m.student_id===s.id)?.status||'unmarked';return <tr key={s.id}><td>{s.roll}</td><td>{s.name}</td><td><div className="mark-buttons" role="group" aria-label={'Submission for '+s.name}>{(['submitted','missing','unmarked'] as const).map(value=><button key={value} className={'mark-button '+(status===value?'selected '+value:'')} disabled={busy} aria-pressed={status===value} aria-label={value==='submitted'?'Submitted':value==='missing'?'Not submitted':'Unmarked'} title={value==='submitted'?'Submitted':value==='missing'?'Not submitted':'Unmarked'} onClick={()=>action('mark',{taskId:current.id,studentId:s.id,status:value})}>{value==='submitted'?'✓':value==='missing'?'✕':'—'}</button>)}</div></td></tr>})}</tbody></table></div>:<p className="muted">Add students to this class in the attendance workspace. New students appear unmarked automatically.</p>}{students.length&&!filtered.length?<p className="muted">No students match your search.</p>:null}</>:<p className="muted">Select or create a task to see its submission list.</p>}</section></div>}</main></>
}
